
let data=[],trials=[],eid=null,currentRole=null,editVersion=0,refreshTimer=null,refreshing=false,pendingTrialId=null,editingTrialId=null;let selectedMembers=new Set(),selectedTrials=new Set();const $=x=>document.getElementById(x),money=x=>Number(x||0).toLocaleString("fr-FR")+" €";
let cameraStream=null,cameraKind=null,cameraFiles={photo:null,medical:null};let coachDocMemberId=null,coachDocKind=null,coachDocCameraFile=null;let loadedBackup=null,backupRestoreBusy=false;
function isPhoneDevice(){return /Android|iPhone|iPod|IEMobile|Opera Mini|Mobile/i.test(navigator.userAgent||"")&&!/iPad/i.test(navigator.userAgent||"")}
function setupDocumentInputs(){let mobile=isPhoneDevice();[["photo","image/*"],["medical","image/*,application/pdf"]].forEach(([kind,accept])=>{let input=$(kind+"File"),actions=$(kind+"DesktopActions");if(!input)return;input.accept=accept;if(mobile){input.classList.remove("desktop-doc-input");input.setAttribute("capture","environment");if(actions)actions.style.display="none"}else{input.classList.add("desktop-doc-input");input.removeAttribute("capture");if(actions)actions.style.display="flex"}})}
function browseDocument(kind){let input=$(kind+"File");if(input){cameraFiles[kind]=null;input.click()}}
function selectedDocumentFile(kind){return cameraFiles[kind]||($(kind+"File")?.files?.[0]||null)}
function updateDocumentState(kind,existingText){let input=$(kind+"File"),state=$(kind+"State"),f=cameraFiles[kind]||(input?.files?.[0]);if(!state)return;if(f){state.textContent=`Sélectionné : ${f.name} (${Math.max(1,Math.round(f.size/1024))} Ko)`;return}state.textContent=existingText|| (kind==="photo"?"Photo à prendre avec l’appareil photo — 8 Mo maximum.":"Certificat à photographier — 12 Mo maximum.")}
async function startCamera(kind){cameraKind=kind;cameraError.textContent="";let baseKind=String(kind||"").replace(/^coach-/,"");cameraTitle.textContent=baseKind==="photo"?"Photo de l’adhérent":"Photo du certificat médical";try{if(!navigator.mediaDevices?.getUserMedia)throw new Error("La caméra n’est pas disponible dans ce navigateur.");cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});cameraVideo.srcObject=cameraStream;cameraM.classList.add("open")}catch(err){closeCamera();alert("Impossible d’ouvrir la caméra : "+err.message)}}
function closeCamera(){if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}cameraVideo.srcObject=null;cameraM.classList.remove("open");cameraKind=null}
function captureCamera(){if(!cameraKind||!cameraStream)return;let v=cameraVideo,w=v.videoWidth||1280,h=v.videoHeight||720;if(!w||!h){cameraError.textContent="La caméra n’est pas encore prête.";return}cameraCanvas.width=w;cameraCanvas.height=h;cameraCanvas.getContext("2d").drawImage(v,0,0,w,h);let rawKind=cameraKind,isCoach=String(rawKind).startsWith("coach-"),kind=String(rawKind).replace(/^coach-/,"");cameraCanvas.toBlob(blob=>{if(!blob){cameraError.textContent="Impossible de prendre la photo.";return}let stamp=new Date().toISOString().replace(/[:.]/g,"-");let name=kind==="photo"?`photo-camera-${stamp}.jpg`:`certificat-camera-${stamp}.jpg`,file=new File([blob],name,{type:"image/jpeg",lastModified:Date.now()});if(isCoach){coachDocCameraFile=file;if(coachDocFile)coachDocFile.value="";updateCoachDocumentState()}else{cameraFiles[kind]=file;let input=$(kind+"File");if(input)input.value="";updateDocumentState(kind)}closeCamera()},"image/jpeg",0.9)}

function age(b){if(!b)return 0;let d=new Date(b),t=new Date(),a=t.getFullYear()-d.getFullYear();if(new Date(t.getFullYear(),d.getMonth(),d.getDate())>t)a--;return a}
function normalizePhone(v){return String(v||"").replace(/\D/g,"")}
function formatPhone(v){let d=normalizePhone(v).slice(0,10);return d.replace(/(\d{2})(?=\d)/g,"$1 ")}
function validPhone(v){let d=normalizePhone(v);return !d||/^0\d{9}$/.test(d)}
function validEmail(v){let e=String(v||"").trim();return !e||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)}
function displaySex(v){return v==="Fille"?"Femme":v==="Garçon"?"Homme":v}
const ADO_ACTS=["Boxe ados","MMA Ado","Striking ados"],ADULT_ACTS=["Boxe adultes","Grappling","Striking adultes"];
function disciplinePrice(selected){let a=selected||[],hasBaby=a.includes("Baby boxe"),hasChild=a.includes("Boxe enfants"),ado=a.filter(x=>ADO_ACTS.includes(x)),adult=a.filter(x=>ADULT_ACTS.includes(x));if(!a.length)return{valid:false,value:0,reason:"Sélectionnez au moins une discipline."};if(hasBaby&&a.length>1)return{valid:false,value:0,reason:"Baby boxe ne peut pas être combinée avec une autre discipline."};if(hasChild&&a.length>1)return{valid:false,value:0,reason:"Boxe enfants ne peut pas être combinée avec une autre discipline."};if(ado.length&&adult.length)return{valid:false,value:0,reason:"Les disciplines Ado et Adultes ne peuvent pas être combinées."};if(hasBaby)return{valid:true,value:130};if(hasChild)return{valid:true,value:220};if(ado.length)return{valid:true,value:ado.length===1?220:ado.length===2?340:380};if(adult.length)return{valid:true,value:adult.length===1?270:adult.length===2?350:400};return{valid:false,value:0,reason:"Combinaison de disciplines non reconnue."}}
function sameFamilyAddress(a,b){return !!(a&&b&&a.address&&a.zip&&a.city&&b.address&&b.zip&&b.city&&(a.address||"").trim().toLowerCase()===(b.address||"").trim().toLowerCase()&&String(a.zip||"").trim()===String(b.zip||"").trim()&&(a.city||"").trim().toLowerCase()===(b.city||"").trim().toLowerCase())}
function createdRank(m){let t=Date.parse(m&&m.created_at||"");return Number.isFinite(t)?t:Number.MAX_SAFE_INTEGER}
function familyMembers(m){if(!m||!m.address||!m.zip||!m.city)return [m];let list=data.filter(x=>x.id!==m.id&&sameFamilyAddress(x,m));list.push(m);return list.sort((a,b)=>createdRank(a)-createdRank(b)||String(a.id||"").localeCompare(String(b.id||"")))}
function familyInfo(m){let list=familyMembers(m),pos=Math.max(0,list.findIndex(x=>x===m||x.id===m.id))+1;if(!pos)pos=list.length;return{size:list.length,position:pos,discount:pos>=2&&pos<=4?20:0}}
function family(m){return familyInfo(m).size}
function calc(m){let fi=familyInfo(m),disc=fi.discount,pricing=disciplinePrice(m.acts||[]),theory=pricing.valid?pricing.value:0,sug=Math.max(0,theory-disc),stored=m.due==null?null:Number(m.due),due;if(stored==null||!Number.isFinite(stored))due=sug;else if(!disc&&theory>=20&&Math.abs(stored-(theory-20))<0.001)due=theory;else due=Math.min(stored,sug);let paid=(m.payments||[]).reduce((s,p)=>s+(+p.amount||0),0),rest=Math.max(0,due-paid),paymentStatus=due===0?"Gratuit":paid>=due?"À jour":paid?"Partiel":"Impayé";return{disc,theory,sug,due,paid,rest,paymentStatus,status:paymentStatus,familyPosition:fi.position,familySize:fi.size}}
function statusReasons(m,x=calc(m),includeMedical=true){let reasons=[];if(x.rest>0)reasons.push("Défaut de paiement");if(includeMedical&&!m.medical_path)reasons.push("Certificat médical manquant");if(!m.photo_path)reasons.push("Photo manquante");return reasons}
function fullMemberStatus(m,x=calc(m)){let reasons=statusReasons(m,x,true);return{ok:reasons.length===0,reasons,label:reasons.length?"Pas à jour":"À jour"}}
function statusHtml(m,x=calc(m)){let s=fullMemberStatus(m,x);return s.ok?"<span class='status-ok'>● À jour</span>":`<span class='status-due'>⚠ Pas à jour</span><div class='small'>${s.reasons.join(" · ")}</div>`}
function render(){let z=data.map(m=>({m,x:calc(m),s:fullMemberStatus(m)}));n.textContent=data.length;girls.textContent=data.filter(x=>displaySex(x.sex)==="Femme").length;boys.textContent=data.filter(x=>displaySex(x.sex)==="Homme").length;paidMembers.textContent=z.filter(o=>o.s.ok).length;dueMembers.textContent=z.filter(o=>o.x.rest>0).length;alreadyPaid.textContent=money(z.reduce((s,o)=>s+o.x.paid,0));notPaid.textContent=money(z.reduce((s,o)=>s+o.x.rest,0));let all=data.flatMap(m=>m.payments||[]);let totalBy=name=>all.filter(p=>p.method===name).reduce((s,p)=>s+(Number(p.amount)||0),0);cashTotal.textContent=money(totalBy("Espèces"));checkTotal.textContent=money(totalBy("Chèque"));couponTotal.textContent=money(totalBy("Coupons Sport"));labazTotal.textContent=money(totalBy("LABAZ"));passTotal.textContent=money(totalBy("Pass Sport"));ancvTotal.textContent=money(totalBy("Chèque ANCV"));deleteAllBtn.disabled=!data.length;deleteAllTrialsBtn.disabled=!trials.length;adminRows();coachRows();trialRowsRender();applyRole()}
function selectedValues(el){return el?[...el.selectedOptions].map(o=>o.value):[]}
function trialForMember(m){return trials.find(t=>samePerson(t,m))||null}
function trialActsForMember(m){let t=trialForMember(m);return t?(t.acts||[]):[]}
function disciplineTags(list,trial=false){return (list||[]).map(x=>`<span class="discipline-tag${trial?' trial':''}">${x}</span>`).join(" ")}
function updateMemberSelectionUi(){let b=$("deleteSelectedBtn");if(b){b.textContent=`Supprimer la sélection (${selectedMembers.size})`;b.disabled=!selectedMembers.size}let all=$("memberSelectAll"),visible=data.filter(memberMatchesSearch);if(all)all.checked=visible.length>0&&visible.every(m=>selectedMembers.has(m.id))}
function memberMatchesSearch(m){let q=(aq.value||"").trim().toLowerCase(),filters=selectedValues($("memberDiscFilter"));let text=(m.first+" "+m.last).toLowerCase();let qok=!q||text.includes(q);let allActs=[...(m.acts||[]),...trialActsForMember(m)];let fok=!filters.length||filters.some(d=>allActs.includes(d));return qok&&fok}
function adminRows(){let visible=data.filter(memberMatchesSearch);rows.innerHTML=visible.map(m=>{let x=calc(m),trialActs=trialActsForMember(m),st=statusHtml(m,x);return`<tr><td class="select-col"><input type="checkbox" style="width:auto" ${selectedMembers.has(m.id)?"checked":""} onchange="toggleMemberSelection('${m.id}',this.checked)"></td><td>${st}</td><td><button class="link" onclick="profileShow('${m.id}','admin')">${m.first} ${m.last}</button></td><td>${displaySex(m.sex)}</td><td>${age(m.birth)} ans</td><td>${formatPhone(m.phone)}</td><td>${disciplineTags(m.acts||[])}</td><td>${trialActs.length?disciplineTags(trialActs,true):""}</td><td>${x.disc?"−20 €":"—"}</td><td>${money(x.due)}</td><td>${money(x.paid)}</td><td>${money(x.rest)}</td><td><button onclick="openForm('${m.id}')">Modifier</button> <button class="danger" onclick="deleteOneMember('${m.id}')">Supprimer</button></td></tr>`}).join("")||"<tr><td colspan=13>Aucun adhérent</td></tr>";updateMemberSelectionUi()}
function toggleMemberSelection(id,on){on?selectedMembers.add(id):selectedMembers.delete(id);updateMemberSelectionUi()}
function toggleAllMembers(on){data.filter(memberMatchesSearch).forEach(m=>on?selectedMembers.add(m.id):selectedMembers.delete(m.id));adminRows()}
function coachRows(){let q=cq.value.toLowerCase();coachCards.innerHTML=data.filter(m=>(m.first+" "+m.last+" "+m.phone+" "+m.acts.join(" ")+" "+trialActsForMember(m).join(" ")).toLowerCase().includes(q)).map(m=>{let x=calc(m),ta=trialActsForMember(m);let st=(x.status==="À jour"||x.status==="Gratuit")?"<div class='status-ok' style='margin-top:8px'>● À jour</div>":"<div class='status-due' style='margin-top:8px'>⚠ Pas à jour — défaut de paiement</div>";let med=m.has_medical?"":"<div class='medical-warning'>⚠ Certificat médical manquant</div>";let pic=m.photo_url?`<img class="member-photo" src="${m.photo_url}" alt="Photo de ${m.first}">`:'<div style="font-size:40px">📷</div>';return`<div class="card">${pic}<br><button class="link" onclick="profileShow('${m.id}','coach')">${m.first} ${m.last}</button><div>${displaySex(m.sex)} · ${age(m.birth)} ans</div><div>${formatPhone(m.phone)}</div><div class="small"><b>Inscrit :</b> ${m.acts.join(" · ")}</div>${ta.length?`<div class="small"><b>En essai :</b> ${ta.join(" · ")}</div>`:""}${st}${med}</div>`}).join("")||"Aucun adhérent"}

function mayDelete(){return currentRole==="owner"||currentRole==="admin"}
async function deleteOneMember(id){let m=data.find(x=>x.id===id);if(!m)return;if(!mayDelete()){alert("Suppression réservée au Propriétaire et à l’Administrateur.");return}if(!confirm(`Supprimer définitivement ${m.first} ${m.last} ?\n\nSa fiche, sa photo et son certificat médical seront supprimés. Cette opération est irréversible.`))return;document.body.classList.add("busy");try{await CloudStore.deleteMember(id);await refreshData();alert(`${m.first} ${m.last} a été supprimé(e).`)}catch(err){await refreshData();alert("Suppression impossible : "+err.message)}finally{document.body.classList.remove("busy")}}
async function deleteSelectedMembers(){if(!mayDelete()){alert("Suppression réservée au Propriétaire et à l’Administrateur.");return}let ids=[...selectedMembers].filter(id=>data.some(m=>m.id===id));if(!ids.length)return;if(!confirm(`Supprimer définitivement ${ids.length} adhérent${ids.length>1?"s":""} sélectionné${ids.length>1?"s":""} ?\n\nLes photos et certificats associés seront également supprimés.`))return;let typed=prompt("Pour confirmer cette suppression par bloc, saisissez exactement SUPPRIMER :");if(typed===null)return;if(typed.trim()!=="SUPPRIMER"){alert("Validation incorrecte. Aucune donnée n’a été supprimée.");return}document.body.classList.add("busy");let failures=[];try{for(let id of ids){try{await CloudStore.deleteMember(id)}catch(err){failures.push(err.message)}}selectedMembers.clear();await refreshData();alert(failures.length?`Suppression terminée avec ${failures.length} erreur(s).`:`${ids.length} adhérent${ids.length>1?"s":""} supprimé${ids.length>1?"s":""}.`)}finally{document.body.classList.remove("busy")}}
async function deleteAllMembers(){if(!mayDelete()){alert("Suppression réservée au Propriétaire et à l’Administrateur.");return}let total=data.length;if(!total)return;let typed=prompt(`ATTENTION : vous allez supprimer définitivement ${total} adhérent${total>1?"s":""}, ainsi que toutes les photos et tous les certificats.\n\nPour continuer, saisissez exactement SUPPRIMER :`);if(typed===null)return;if(typed.trim()!=="SUPPRIMER"){alert("Validation incorrecte. Aucune donnée n’a été supprimée.");return}if(!confirm(`Dernière confirmation : supprimer définitivement les ${total} adhérent${total>1?"s":""} ?`))return;document.body.classList.add("busy");try{let result=await CloudStore.deleteAllMembers(),count=result.count??total;await refreshData();alert(`${count} adhérent${count>1?"s":""} supprimé${count>1?"s":""}.`)}catch(err){await refreshData();alert("Suppression incomplète ou impossible : "+err.message)}finally{document.body.classList.remove("busy")}}

function normPerson(v){return String(v||"").trim().normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function samePerson(a,b){return normPerson(a.last||a.last_name)===normPerson(b.last||b.last_name)&&normPerson(a.first||a.first_name)===normPerson(b.first||b.first_name)}
function trialDays(t){let d=new Date((t.start||t.trial_start)+"T00:00:00"),now=new Date();now.setHours(0,0,0,0);return Math.max(0,Math.floor((now-d)/86400000))}
function formatFrDate(v){if(!v)return"";let d=new Date(v+"T00:00:00");return d.toLocaleDateString("fr-FR")}
function trialExpired(t){let d=new Date((t.start||t.trial_start)+"T00:00:00"),limit=new Date(d);limit.setMonth(limit.getMonth()+1);let now=new Date();now.setHours(0,0,0,0);return now>=limit}
function activeMemberMatch(lastName,firstName){return data.find(m=>samePerson(m,{last:lastName,first:firstName}))||null}
function trialMatchesSearch(t){let q=(trialQ.value||"").trim().toLowerCase(),filters=selectedValues($("trialDiscFilter"));let qok=!q||((t.first||"")+" "+(t.last||"")).toLowerCase().includes(q);let fok=!filters.length||filters.some(d=>(t.acts||[]).includes(d));return qok&&fok}
function updateTrialSelectionUi(){let b=$("deleteSelectedTrialsBtn");if(b){b.textContent=`Supprimer la sélection (${selectedTrials.size})`;b.disabled=!selectedTrials.size}let visible=trials.filter(trialMatchesSearch),all=$("trialSelectAll");if(all)all.checked=visible.length>0&&visible.every(t=>selectedTrials.has(t.id))}
function trialRowsRender(){if(!$("trialRows"))return;let visible=trials.filter(trialMatchesSearch);trialRows.innerHTML=visible.map(t=>{let days=trialDays(t),over=trialExpired(t),status=over?"⚠ Essai ≥ 1 mois":"En essai",transform=currentRole==="coach"?"":`<button onclick="transformTrial('${t.id}')">Transformer en adhérent</button>`;return`<tr class="${over?"trial-overdue":""}"><td class="select-col"><input type="checkbox" style="width:auto" ${selectedTrials.has(t.id)?"checked":""} onchange="toggleTrialSelection('${t.id}',this.checked)"></td><td>${t.last}</td><td>${t.first}</td><td>${formatFrDate(t.start)}</td><td>${days} jour${days>1?"s":""}</td><td>${disciplineTags(t.acts||[],true)}</td><td>${status}</td><td><div class="trial-actions"><button onclick="openTrialEdit('${t.id}')">Modifier disciplines</button>${transform}<button class="danger" onclick="deleteOneTrial('${t.id}')">Supprimer</button></div></td></tr>`}).join("")||"<tr><td colspan=8>Aucune personne en période d’essai</td></tr>";updateTrialSelectionUi()}
function toggleTrialSelection(id,on){on?selectedTrials.add(id):selectedTrials.delete(id);updateTrialSelectionUi()}
function toggleAllTrials(on){trials.filter(trialMatchesSearch).forEach(t=>on?selectedTrials.add(t.id):selectedTrials.delete(t.id));trialRowsRender()}
function invalidTrialDisciplinesForMember(member,acts){if(!member)return[];return (acts||[]).filter(a=>(member.acts||[]).includes(a))}
async function addTrial(){let lastName=trialLast.value.trim(),firstName=trialFirst.value.trim(),start=trialStart.value,actsSel=selectedValues(trialActs);if(!lastName||!firstName||!start||!actsSel.length){alert("Nom, prénom, date de début et au moins une discipline d’essai sont obligatoires.");return}if(trials.some(t=>samePerson(t,{last:lastName,first:firstName}))){alert("Cette personne est déjà enregistrée en période d’essai. Utilisez Modifier disciplines pour ajouter une nouvelle discipline.");return}let member=activeMemberMatch(lastName,firstName),blocked=invalidTrialDisciplinesForMember(member,actsSel);if(blocked.length){alert("Essai impossible dans une discipline où la personne est déjà inscrite : "+blocked.join(", ")+".");return}document.body.classList.add("busy");try{await CloudStore.saveTrial({last:lastName,first:firstName,start,acts:actsSel});trialLast.value="";trialFirst.value="";trialStart.value=new Date().toISOString().slice(0,10);[...trialActs.options].forEach(o=>o.selected=false);await refreshData()}catch(err){alert("Ajout impossible : "+err.message)}finally{document.body.classList.remove("busy")}}
function openTrialEdit(id){let t=trials.find(x=>x.id===id);if(!t)return;editingTrialId=id;trialEditName.textContent=`${t.first} ${t.last} — début le ${formatFrDate(t.start)}`;[...trialEditActs.options].forEach(o=>o.selected=(t.acts||[]).includes(o.value));trialEditM.classList.add("open")}
function closeTrialEdit(){editingTrialId=null;trialEditM.classList.remove("open")}
async function saveTrialEdit(){let t=trials.find(x=>x.id===editingTrialId);if(!t)return;let actsSel=selectedValues(trialEditActs);if(!actsSel.length){alert("Conservez au moins une discipline d’essai, ou supprimez la fiche d’essai.");return}let member=activeMemberMatch(t.last,t.first),blocked=invalidTrialDisciplinesForMember(member,actsSel);if(blocked.length){alert("Cette personne est déjà inscrite dans : "+blocked.join(", ")+". Retirez ces disciplines de la période d’essai.");return}document.body.classList.add("busy");try{await CloudStore.updateTrialDisciplines(t.id,actsSel);closeTrialEdit();await refreshData()}catch(err){alert("Modification impossible : "+err.message)}finally{document.body.classList.remove("busy")}}
async function deleteOneTrial(id){let t=trials.find(x=>x.id===id);if(!t)return;if(!confirm(`Supprimer ${t.first} ${t.last} de la période d’essai ?`))return;document.body.classList.add("busy");try{await CloudStore.deleteTrial(id);selectedTrials.delete(id);await refreshData()}catch(err){alert("Suppression impossible : "+err.message)}finally{document.body.classList.remove("busy")}}
async function deleteSelectedTrials(){let ids=[...selectedTrials].filter(id=>trials.some(t=>t.id===id));if(!ids.length)return;if(!confirm(`Supprimer ${ids.length} personne${ids.length>1?"s":""} sélectionnée${ids.length>1?"s":""} de la période d’essai ?`))return;document.body.classList.add("busy");try{await CloudStore.deleteTrials(ids);selectedTrials.clear();await refreshData()}catch(err){alert("Suppression impossible : "+err.message)}finally{document.body.classList.remove("busy")}}
async function deleteAllTrials(){if(!trials.length)return;if(!confirm(`Supprimer toutes les ${trials.length} personnes actuellement en période d’essai ? Cette opération est irréversible.`))return;document.body.classList.add("busy");try{await CloudStore.deleteAllTrials();selectedTrials.clear();await refreshData()}catch(err){alert("Suppression impossible : "+err.message)}finally{document.body.classList.remove("busy")}}
function transformTrial(id){if(currentRole==="coach"){alert("La création d’un adhérent est réservée au Propriétaire et à l’Administrateur.");return}let t=trials.find(x=>x.id===id);if(!t)return;pendingTrialId=id;openForm(null,true);last.value=t.last;first.value=t.first;formWarning.textContent="Disciplines testées : "+((t.acts||[]).join(", ")||"Aucune discipline renseignée")+". Choisissez librement les disciplines d’inscription."}
async function reconcileTrialAfterMemberSaved(m){let t=(pendingTrialId&&trials.find(x=>x.id===pendingTrialId))||trials.find(x=>samePerson(x,m));pendingTrialId=null;if(!t)return;let overlap=(t.acts||[]).filter(a=>(m.acts||[]).includes(a));if(!overlap.length)return;let remaining=(t.acts||[]).filter(a=>!overlap.includes(a));let msg=`${t.first} ${t.last} était en essai dans : ${overlap.join(", ")}.\n\nVoulez-vous retirer de la période d’essai les disciplines auxquelles la personne vient de s’inscrire ?`;if(!confirm(msg))return;try{if(remaining.length)await CloudStore.updateTrialDisciplines(t.id,remaining);else{await CloudStore.deleteTrial(t.id);selectedTrials.delete(t.id)}}catch(err){alert("L’adhérent a bien été enregistré, mais la mise à jour de la période d’essai a échoué : "+err.message)}}

function paymentDetail(m){
 let ps=m.payments||[];
 if(!ps.length)return "<p><b>Détail des paiements :</b> Aucun paiement enregistré.</p>";
 return "<div><b>Détail des paiements :</b>"+ps.map(p=>{
   if(p.method==="Chèque"){
     let cs=(p.checks||[]).map((c,i)=>`<li>Chèque ${i+1} : ${money(c.amount)}${c.no?" — n° "+c.no:""}${c.bank?" — "+c.bank:""}</li>`).join("");
     return `<div class="pay"><b>Chèque — ${money(p.amount)}</b><ul>${cs}</ul></div>`;
   }
   if(p.method==="Chèque ANCV")return `<div class="pay"><b>Chèque ANCV${p.ancvType?" — "+p.ancvType:""} :</b> ${money(p.amount)}</div>`;
   return `<div class="pay"><b>${p.method} :</b> ${money(p.amount)}</div>`;
 }).join("")+"</div>";
}
function profileShow(id,role){
 let m=data.find(x=>x.id===id),x=calc(m),ta=trialActsForMember(m);
 let trialHtml=ta.length?`<p><b>Disciplines en essai :</b> ${disciplineTags(ta,true)}</p>`:"";
 if(role==="coach"){
   let st=(x.status==="À jour"||x.status==="Gratuit")?"<span class='status-ok'>● À jour</span>":"<span class='status-due'>⚠ Pas à jour — défaut de paiement</span>",med=m.has_medical?"":"<div class='medical-warning'>⚠ Certificat médical manquant</div>";
   profile.innerHTML=`${m.photo_url?`<img class="member-photo" src="${m.photo_url}" alt="Photo">`:'<div style="font-size:50px">📷</div>'}<h2>${m.first} ${m.last}</h2><p>${displaySex(m.sex)} · ${age(m.birth)} ans</p><p>📞 ${formatPhone(m.phone)}</p><p><b>Disciplines inscrites :</b> ${disciplineTags(m.acts||[])}</p>${trialHtml}<p><b>Statut :</b> ${st}</p>${med}<div class="coach-doc-actions"><button type="button" onclick="openCoachDocument('${m.id}','photo')">Ajouter / Modifier la photo</button><button type="button" onclick="openCoachDocument('${m.id}','medical')">Ajouter / Modifier le certificat médical</button></div>`;
 }else{
   let fs=fullMemberStatus(m,x),reasonHtml=fs.reasons.length?`<br><b>Raison(s) :</b> ${fs.reasons.join(" · ")}`:"";
   profile.innerHTML=`${m.photo_url?`<img class="member-photo" src="${m.photo_url}" alt="Photo">`:'<div style="font-size:50px">📷</div>'}<h2>${m.first} ${m.last}</h2><p>${displaySex(m.sex)} · ${age(m.birth)} ans</p><p><b>Tél :</b> ${formatPhone(m.phone)}<br><b>Email :</b> ${m.email||""}<br><b>Adresse :</b> ${m.address||""}, ${m.zip||""} ${m.city||""}</p><p><b>Disciplines inscrites :</b> ${disciplineTags(m.acts||[])}</p>${trialHtml}<p><b>Réduction famille :</b> ${x.disc?"Oui −20 €":"Non"}<br><b>Tarif théorique :</b> ${money(x.theory)}<br><b>À payer :</b> ${money(x.due)}<br><b>Payé :</b> ${money(x.paid)}<br><b>Reste :</b> ${money(x.rest)}<br><b>Statut :</b> ${fs.ok?"À jour":"Pas à jour"}${reasonHtml}</p>${paymentDetail(m)}<p><b>Certificat médical :</b> ${m.medical_url?`<a href="${m.medical_url}" target="_blank" rel="noopener">Ouvrir ${m.medical_name||''}</a>`:'Non enregistré'}</p><p><b>Commentaires :</b> ${m.comments||"—"}</p>`;
 }
 profileM.classList.add("open")
}
function openCoachDocument(memberId,kind){if(currentRole!=="coach"){alert("Cette fonction est réservée au Coach.");return}let m=data.find(x=>x.id===memberId);if(!m)return;coachDocMemberId=memberId;coachDocKind=kind;coachDocCameraFile=null;coachDocFile.value="";coachDocTitle.textContent=kind==="photo"?"Photo de l’adhérent":"Certificat médical";coachDocMember.textContent=`${m.first||""} ${m.last||""}`.trim();let mobile=isPhoneDevice();coachDocFile.accept=mobile?"image/*":(kind==="photo"?"image/*":"image/*,application/pdf");if(mobile){coachDocFile.setAttribute("capture","environment");coachDocDesktopActions.style.display="none";coachDocMobileCamera.classList.remove("hide");coachDocMobileCamera.textContent=kind==="photo"?"Prendre une photo":"Photographier le certificat"}else{coachDocFile.removeAttribute("capture");coachDocDesktopActions.style.display="flex";coachDocMobileCamera.classList.add("hide")}updateCoachDocumentState();coachDocM.classList.add("open")}
function closeCoachDocument(){closeCamera();coachDocM.classList.remove("open");coachDocMemberId=null;coachDocKind=null;coachDocCameraFile=null;coachDocFile.value="";coachDocSave.disabled=true}
function browseCoachDocument(){coachDocCameraFile=null;coachDocFile.click()}
function startCoachDocumentCamera(){if(!coachDocKind)return;startCamera("coach-"+coachDocKind)}
function selectedCoachDocumentFile(){return coachDocCameraFile||(coachDocFile.files&&coachDocFile.files[0])||null}
function updateCoachDocumentState(){let f=selectedCoachDocumentFile();coachDocSave.disabled=!f;if(!f){coachDocState.textContent=coachDocKind==="medical"?"Aucun certificat sélectionné.":"Aucune photo sélectionnée.";return}coachDocState.textContent=`Sélectionné : ${f.name} (${Math.max(1,Math.round(f.size/1024))} Ko)`}
coachDocFile.addEventListener("change",()=>{coachDocCameraFile=null;updateCoachDocumentState()});
async function saveCoachDocument(){if(currentRole!=="coach"||!coachDocMemberId||!coachDocKind)return;let file=selectedCoachDocumentFile();if(!file){alert("Sélectionnez ou prenez une photo avant d’enregistrer.");return}let id=coachDocMemberId,kind=coachDocKind,m=data.find(x=>x.id===id);if(!m)return;let label=kind==="photo"?"la photo":"le certificat médical";if(!confirm(`Enregistrer ${label} pour ${m.first} ${m.last} ?`))return;coachDocSave.disabled=true;coachDocM.classList.add("busy");try{let result=await CloudStore.saveCoachDocument(id,kind,file);closeCoachDocument();await refreshData();profileShow(id,"coach");let msg=`${kind==="photo"?"Photo":"Certificat médical"} enregistré(e).`;if(result&&result.cleanup_warning)msg+="\n\nAttention : l’ancien fichier n’a pas pu être supprimé du stockage. La fiche adhérent reste correcte.";alert(msg)}catch(err){alert("Enregistrement impossible : "+err.message);coachDocSave.disabled=false}finally{coachDocM.classList.remove("busy")}}
function suggested(){let selected=[...acts.selectedOptions].map(o=>o.value),pricing=disciplinePrice(selected),old=eid?data.find(x=>x.id===eid):null,tmp={id:eid||"new",last:last.value,address:address.value,zip:zip.value,city:city.value,created_at:old&&old.created_at||""},fi=familyInfo(tmp),d=fi.discount;return{v:pricing.valid?Math.max(0,pricing.value-d):0,d,fn:fi.position,familySize:fi.size,valid:pricing.valid,reason:pricing.reason||""}}
function update(){let s=suggested();ageV.textContent=birth.value?age(birth.value)+" ans":"—";suggest.textContent=s.valid?money(s.v):s.reason;fam.textContent=s.d?`Réduction famille −20 € (membre n°${s.fn})`:"Pas de réduction famille";due.max=s.valid?s.v:0;if(!s.valid&&due.dataset.auto==="1")due.value="";else if(s.valid&&(due.dataset.auto==="1"||due.value===""))due.value=s.v;payPreview()}
const CHECK_BANKS=["Crédit Agricole","BNP Paribas","Société Générale","Crédit Mutuel","CIC","Banque Populaire","Caisse d’Épargne","La Banque Postale","LCL","BoursoBank","Hello bank!","Fortuneo","Crédit Coopératif","CCF","Banque Palatine"];
function bankField(value=""){let bank=String(value||"").trim(),known=CHECK_BANKS.includes(bank),selected=bank?(known?bank:"Autre"):"";return`<div><select class="cbank" onchange="bankChange(this)"><option value="">Banque</option>${CHECK_BANKS.map(x=>`<option value="${x}" ${selected===x?"selected":""}>${x}</option>`).join("")}<option value="Autre" ${selected==="Autre"?"selected":""}>Autre</option></select><input class="cbankOther ${selected==="Autre"?"":"hide"}" style="margin-top:6px" type="text" placeholder="Nom de la banque" value="${selected==="Autre"?bank:""}"></div>`}
function bankChange(select){let other=select.closest(".checks").querySelector(".cbankOther");other.classList.toggle("hide",select.value!=="Autre");if(select.value!=="Autre")other.value="";payPreview()}
function checkFields(p={}){let cs=p.checks||[{}];return`<label>Nombre de chèques</label><select class="count" onchange="checksMake(this)">${[1,2,3,4].map(n=>`<option ${n===cs.length?"selected":""}>${n}</option>`).join("")}</select><div class="checkBox">${cs.map((c,i)=>`<div class="checks"><input class="cno" placeholder="N° chèque ${i+1}" value="${c.no||""}">${bankField(c.bank)}<input class="camt" type="number" min="0" placeholder="Montant" value="${c.amount||""}"></div>`).join("")}</div>`}
function ancvFields(p={}){return`<label>Type de Chèque ANCV</label><select class="ancvType" required><option value="">Sélectionner</option><option ${p.ancvType==="Physique"?"selected":""}>Physique</option><option ${p.ancvType==="Dématérialisé"?"selected":""}>Dématérialisé</option></select>`}
function codeFields(p={}){return`<label>Code obligatoire</label><input class="payCode" type="text" placeholder="Code ${p.method||''}" value="${p.code||''}">`}
function payHtml(p={}){return`<div class="pay"><div class="grid"><select class="method" onchange="methodChange(this)"><option value="">Mode</option>${["Espèces","Chèque","Coupons Sport","LABAZ","Pass Sport","Chèque ANCV"].map(x=>`<option ${p.method===x?"selected":""}>${x}</option>`).join("")}</select><input class="pamt" type="number" min="0" placeholder="Montant" value="${p.method==="Chèque"?"":p.amount||""}"></div><div class="checkArea">${p.method==="Chèque"?checkFields(p):p.method==="Chèque ANCV"?ancvFields(p):(p.method==="LABAZ"||p.method==="Pass Sport")?codeFields(p):""}</div><button type="button" onclick="this.closest('.pay').remove();payPreview()">Supprimer</button></div>`}
function addPay(p={}){pays.insertAdjacentHTML("beforeend",payHtml(p));bindPay()}function methodChange(e){let a=e.closest(".pay").querySelector(".checkArea");a.innerHTML=e.value==="Chèque"?checkFields({}):e.value==="Chèque ANCV"?ancvFields({}):(e.value==="LABAZ"||e.value==="Pass Sport")?codeFields({method:e.value}):"";bindPay()}function checksMake(e){let n=+e.value,b=e.closest(".pay").querySelector(".checkBox");b.innerHTML=Array.from({length:n},(_,i)=>`<div class="checks"><input class="cno" placeholder="N° chèque ${i+1}">${bankField("")}<input class="camt" type="number" min="0" placeholder="Montant"></div>`).join("");bindPay()}
function bindPay(){document.querySelectorAll(".pay input,.pay select").forEach(e=>e.oninput=payPreview)}function collect(){return[...document.querySelectorAll(".pay")].map(b=>{let method=b.querySelector(".method").value,checks=[],ancvType="",code="";if(method==="Chèque")checks=[...b.querySelectorAll(".checks")].map(r=>{let choice=r.querySelector(".cbank")?.value||"",bank=choice==="Autre"?(r.querySelector(".cbankOther")?.value||"").trim():choice;return{no:r.querySelector(".cno").value,bank,amount:r.querySelector(".camt").value}});if(method==="Chèque ANCV")ancvType=b.querySelector(".ancvType")?.value||"";if(method==="LABAZ"||method==="Pass Sport")code=(b.querySelector(".payCode")?.value||"").trim();let amount=method==="Chèque"?checks.reduce((s,c)=>s+(+c.amount||0),0):(+b.querySelector(".pamt").value||0);return{method,amount,checks,ancvType,code}}).filter(x=>x.method)}
function payPreview(){let paid=collect().reduce((s,p)=>s+p.amount,0),d=+due.value||0;paidV.textContent=money(paid);restV.textContent=money(Math.max(0,d-paid))}
function openForm(id,fromTrial=false){if(!fromTrial)pendingTrialId=null;eid=id||null;let m=id?data.find(x=>x.id===id):{};editVersion=Number(m.version||0);formWarning.textContent="";["last","first","birth","email","address","zip","city","comments"].forEach(k=>$(k).value=m[k]||"");sex.value=displaySex(m.sex||"");phone.value=formatPhone(m.phone||"");addrSearch.value=m.address||"";[...acts.options].forEach(o=>o.selected=(m.acts||[]).includes(o.value));due.value=id?calc(m).due:"";due.dataset.auto="1";pays.innerHTML="";(m.payments||[]).forEach(addPay);photoFile.value="";medicalFile.value="";cameraFiles={photo:null,medical:null};setupDocumentInputs();updateDocumentState("photo",m.photo_path?"Une photo est déjà enregistrée. Choisir un fichier ou utiliser la caméra pour la remplacer.":(isPhoneDevice()?"Prendre une photo — 8 Mo maximum.":"Choisir un fichier ou utiliser la caméra — 8 Mo maximum."));updateDocumentState("medical",m.medical_path?`Certificat enregistré : ${m.medical_name||'document'}. Choisir un fichier ou utiliser la caméra pour le remplacer.`:(isPhoneDevice()?"Prendre une photo du certificat — 12 Mo maximum.":"Choisir un fichier (image/PDF) ou utiliser la caméra — 12 Mo maximum."));update();formM.classList.add("open")}function closeForm(){closeCamera();formM.classList.remove("open");eid=null;editVersion=0;cameraFiles={photo:null,medical:null};formWarning.textContent=""}
form.onsubmit=async e=>{e.preventDefault();if(!validEmail(email.value)){alert("Veuillez saisir une adresse email valide ou laisser le champ vide.");email.focus();return}if(!validPhone(phone.value)){alert("Veuillez saisir un numéro de téléphone français à 10 chiffres commençant par 0, ou laisser le champ vide.");phone.focus();return}let s=suggested();if(!s.valid){alert(s.reason);return}let d=+due.value;if(d>s.v){alert("Le montant à payer ne peut pas dépasser "+money(s.v));return}let ps=collect();if(ps.some(p=>p.method==="Chèque"&&p.checks.some(c=>(+c.amount||0)>0&&!c.bank))){alert("Veuillez sélectionner la banque pour chaque chèque renseigné.");return}if(ps.some(p=>p.method==="Chèque ANCV"&&!p.ancvType)){alert("Veuillez préciser si le Chèque ANCV est Physique ou Dématérialisé.");return}if(ps.some(p=>(p.method==="LABAZ"||p.method==="Pass Sport")&&!p.code)){alert("Le code est obligatoire pour tout paiement LABAZ ou Pass Sport.");return}let paid=ps.reduce((z,p)=>z+p.amount,0);if(paid>d){alert("Le total payé ne peut pas dépasser le montant à payer.");return}let old=eid?data.find(x=>x.id===eid):{};let m={...old,id:eid||crypto.randomUUID(),version:editVersion,last:last.value.trim(),first:first.value.trim(),sex:sex.value,birth:birth.value,phone:normalizePhone(phone.value),email:email.value.trim(),address:address.value,zip:zip.value,city:city.value,catOverride:"",acts:[...acts.selectedOptions].map(o=>o.value),due:d,payments:ps,comments:comments.value};try{form.classList.add("busy");await CloudStore.saveMember(m,selectedDocumentFile("photo"),selectedDocumentFile("medical"));await reconcileTrialAfterMemberSaved(m);closeForm();await refreshData()}catch(err){if(String(err.message).includes("FICHE_MODIFIEE"))formWarning.textContent="Cette fiche a été modifiée par une autre personne. Fermez-la puis ouvrez-la à nouveau avant d’enregistrer.";alert("Enregistrement impossible : "+err.message)}finally{form.classList.remove("busy")}}

photoFile.addEventListener("change",()=>{cameraFiles.photo=null;updateDocumentState("photo")});
medicalFile.addEventListener("change",()=>{cameraFiles.medical=null;updateDocumentState("medical")});
async function addrSuggest(){let q=addrSearch.value.trim();if(q.length<3){addrSug.innerHTML="";return}let query=[q,zip.value,city.value].filter(Boolean).join(" ");try{let r=await fetch("https://api-adresse.data.gouv.fr/search/?q="+encodeURIComponent(query)+"&limit=8"),j=await r.json();addrSug.innerHTML=j.features.map(f=>{let x=f.properties;return`<div data-name="${x.name||""}" data-pc="${x.postcode||""}" data-city="${x.city||""}">${x.label}</div>`}).join("");[...addrSug.children].forEach(d=>d.onclick=()=>{addrSearch.value=d.textContent;address.value=d.dataset.name;zip.value=d.dataset.pc;city.value=d.dataset.city;addrSug.innerHTML="";update()})}catch(e){addrSug.innerHTML=""}}
["birth","last","address","zip","city"].forEach(k=>$(k).oninput=update);phone.oninput=()=>{let pos=phone.selectionStart;phone.value=formatPhone(phone.value)};acts.onchange=()=>{due.dataset.auto="1";update()};due.oninput=()=>{due.dataset.auto="0";payPreview()};addrSearch.oninput=addrSuggest;aq.oninput=adminRows;memberDiscFilter.onchange=adminRows;cq.oninput=coachRows;trialQ.oninput=trialRowsRender;trialDiscFilter.onchange=trialRowsRender;trialStart.value=new Date().toISOString().slice(0,10);document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("on"));b.classList.add("on");document.querySelectorAll("main section").forEach(s=>s.classList.add("hide"));$(b.dataset.p).classList.remove("hide")});
function xmlEscape(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function colName(n){let s="";while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
function crc32(bytes){let c=0xffffffff;for(let b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function u16(n){return [n&255,(n>>>8)&255]}function u32(n){return [n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]}
function zipStore(files,mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"){let enc=new TextEncoder(),parts=[],central=[],offset=0;for(let [name,content] of Object.entries(files)){let nb=enc.encode(name),db=typeof content==="string"?enc.encode(content):content,crc=crc32(db),local=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(db.length),...u32(db.length),...u16(nb.length),...u16(0),...nb]);parts.push(local,db);let cd=new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(db.length),...u32(db.length),...u16(nb.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...nb]);central.push(cd);offset+=local.length+db.length}let csize=central.reduce((s,x)=>s+x.length,0),end=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(central.length),...u16(central.length),...u32(csize),...u32(offset),...u16(0)]);return new Blob([...parts,...central,end],{type:mime})}
function exportExcel(){
 if(currentRole!=="owner"){alert("Export réservé au Propriétaire.");return}
 const headers=["Statut","Nom","Prénom","Sexe","Âge","Téléphone","Email","Adresse","Code postal","Ville","Disciplines","Réduction famille (€)","Tarif théorique (€)","Montant à payer (€)","Payé (€)","Reste (€)","Commentaires"];
 const rows=data.map(m=>{let x=calc(m),st=fullMemberStatus(m,x);return[st.ok?"À jour":"Pas à jour — "+st.reasons.join(" / "),m.last||"",m.first||"",displaySex(m.sex||""),age(m.birth),normalizePhone(m.phone),m.email||"",m.address||"",m.zip||"",m.city||"",(m.acts||[]).join(" / "),x.disc?20:0,x.theory,x.due,x.paid,x.rest,m.comments||""]});
 const moneyCols=[11,12,13,14,15],totalRow=Array(headers.length).fill("");totalRow[0]="TOTAL";moneyCols.forEach(ci=>totalRow[ci]=rows.reduce((sum,r)=>sum+(Number(r[ci])||0),0));
 const all=[totalRow,headers,...rows],widths=[14,18,18,10,8,16,28,32,13,22,38,20,20,22,14,14,40];
 let sheetRows=all.map((r,ri)=>'<row r="'+(ri+1)+'">'+r.map((v,ci)=>{let ref=colName(ci+1)+(ri+1),num=typeof v==="number";let style=ri===1?1:(ri===0?(num?2:(ci===0?1:0)):(ci===4?0:(moneyCols.includes(ci)?2:0)));return num?'<c r="'+ref+'" s="'+style+'"><v>'+v+'</v></c>':'<c r="'+ref+'" t="inlineStr" s="'+style+'"><is><t>'+xmlEscape(v)+'</t></is></c>'}).join("")+'</row>').join("");
 let cols=widths.map((w,i)=>'<col min="'+(i+1)+'" max="'+(i+1)+'" width="'+w+'" customWidth="1"/>').join("");
 const files={
  '[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>',
  '_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
  'xl/workbook.xml':'<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Adhérents" sheetId="1" r:id="rId1"/></sheets></workbook>',
  'xl/_rels/workbook.xml.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
  'xl/styles.xml':'<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/><xf numFmtId="4" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs></styleSheet>',
  'xl/worksheets/sheet1.xml':'<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="2" topLeftCell="A3" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>'+cols+'</cols><sheetData>'+sheetRows+'</sheetData><autoFilter ref="A2:Q'+all.length+'"/></worksheet>'
 };
 const blob=zipStore(files),a=document.createElement("a"),url=URL.createObjectURL(blob);a.href=url;a.download="SGS_Adherents_"+new Date().toISOString().slice(0,10)+".xlsx";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)
}


let ancvExportFilter="all";
function setAncvFilter(v){ancvExportFilter=v;[["ancvAll","all"],["ancvPhysical","Physique"],["ancvDigital","Dématérialisé"]].forEach(([id,val])=>{let b=$(id);if(b)b.classList.toggle("on",v===val)})}
function formatBirthExcel(v){if(!v)return "";let a=String(v).split("-");return a.length===3?`${a[2]}/${a[1]}/${a[0]}`:v}
function fullAddress(m){return [m.address||"",[m.zip||"",m.city||""].filter(Boolean).join(" ")].filter(Boolean).join(", ")}
function makeSimpleXlsx(sheetName,headers,rows,widths,fileName,moneyColIndex){
 const totalRow=Array(headers.length).fill("");totalRow[0]="TOTAL DES MONTANTS";totalRow[moneyColIndex]=rows.reduce((sum,r)=>sum+(Number(r[moneyColIndex])||0),0);
 const all=[totalRow,headers,...rows];
 let sheetRows=all.map((r,ri)=>'<row r="'+(ri+1)+'">'+r.map((v,ci)=>{let ref=colName(ci+1)+(ri+1),num=typeof v==="number",style=ri===1?1:(ri===0?(ci===moneyColIndex?2:(ci===0?1:0)):(ci===moneyColIndex?2:0));return num?'<c r="'+ref+'" s="'+style+'"><v>'+v+'</v></c>':'<c r="'+ref+'" t="inlineStr" s="'+style+'"><is><t>'+xmlEscape(v)+'</t></is></c>'}).join("")+'</row>').join("");
 let cols=widths.map((w,i)=>'<col min="'+(i+1)+'" max="'+(i+1)+'" width="'+w+'" customWidth="1"/>').join("");
 let lastCol=colName(headers.length);
 const files={
  '[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>',
  '_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
  'xl/workbook.xml':'<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="'+xmlEscape(sheetName)+'" sheetId="1" r:id="rId1"/></sheets></workbook>',
  'xl/_rels/workbook.xml.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
  'xl/styles.xml':'<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/><xf numFmtId="4" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs></styleSheet>',
  'xl/worksheets/sheet1.xml':'<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="2" topLeftCell="A3" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>'+cols+'</cols><sheetData>'+sheetRows+'</sheetData><autoFilter ref="A2:'+lastCol+all.length+'"/></worksheet>'
 };
 const blob=zipStore(files),a=document.createElement("a"),url=URL.createObjectURL(blob);a.href=url;a.download=fileName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)
}
function exportPaymentExcel(method){
 if(!(currentRole==="owner"||currentRole==="admin")){alert("Export réservé au Propriétaire et à l’Administrateur.");return}
 let rows=[];
 data.forEach(m=>{
   let ps=(m.payments||[]).filter(p=>p.method===method);
   if(method==="Chèque ANCV"&&ancvExportFilter!=="all")ps=ps.filter(p=>p.ancvType===ancvExportFilter);
   if(!ps.length)return;
   let amount=ps.reduce((sum,p)=>sum+(Number(p.amount)||0),0);
   if(method==="Chèque ANCV"){
     let types=[...new Set(ps.map(p=>p.ancvType||"Non précisé"))].join(" / ");
     rows.push([m.last||"",m.first||"",displaySex(m.sex||""),formatBirthExcel(m.birth),fullAddress(m),amount,types]);
   }else if(method==="LABAZ"||method==="Pass Sport"){
     let codes=[...new Set(ps.map(p=>(p.code||"").trim()).filter(Boolean))].join(" / ");
     rows.push(["Boxe MMA",m.last||"",m.first||"",displaySex(m.sex||""),formatBirthExcel(m.birth),fullAddress(m),codes,amount]);
   }else if(method==="Coupons Sport"){
     rows.push(["Boxe MMA",m.last||"",m.first||"",displaySex(m.sex||""),formatBirthExcel(m.birth),fullAddress(m),amount]);
   }else rows.push([m.last||"",m.first||"",displaySex(m.sex||""),formatBirthExcel(m.birth),fullAddress(m),amount]);
 });
 rows.sort((a,b)=>String(a[0]).localeCompare(String(b[0]),"fr",{sensitivity:"base"})||String(a[1]).localeCompare(String(b[1]),"fr",{sensitivity:"base"}));
 if(!rows.length){let label=method==="Coupons Sport"?"Coupon Sport":method;alert("Aucun adhérent ne correspond à l’export "+label+(method==="Chèque ANCV"&&ancvExportFilter!=="all"?" ("+ancvExportFilter+")":"")+".");return}
 let label=method==="Coupons Sport"?"Coupon Sport":method==="Chèque ANCV"?"ANCV":method;
 let hasCode=method==="LABAZ"||method==="Pass Sport";
 let hasSection=hasCode||method==="Coupons Sport";
 let headers=method==="Chèque ANCV"?["Nom","Prénom","Sexe","Date de naissance","Adresse","Montant payé (€)","Type ANCV"]:hasCode?["Section","Nom","Prénom","Sexe","Date de naissance","Adresse","Code","Montant payé (€)"]:method==="Coupons Sport"?["Section","Nom","Prénom","Sexe","Date de naissance","Adresse","Montant payé (€)"]:["Nom","Prénom","Sexe","Date de naissance","Adresse","Montant payé (€)"];
 let widths=method==="Chèque ANCV"?[20,20,12,18,46,20,20]:hasCode?[16,20,20,12,18,46,24,20]:method==="Coupons Sport"?[16,20,20,12,18,46,20]:[20,20,12,18,46,20];
 let suffix=method==="Chèque ANCV"&&ancvExportFilter!=="all"?"_"+ancvExportFilter.replace(/é/g,"e").replace(/É/g,"E"):"";
 makeSimpleXlsx(label,headers,rows,widths,"SGS_Export_"+label.replace(/ /g,"_")+suffix+"_"+new Date().toISOString().slice(0,10)+".xlsx",hasSection?(hasCode?7:6):5)
}


function safeBackupExt(path,name,type){let m=String(name||path||"").match(/\.([a-zA-Z0-9]{1,8})$/);if(m)return m[1].toLowerCase();if(type==="application/pdf")return"pdf";if(type==="image/png")return"png";if(type==="image/webp")return"webp";return"jpg"}
function backupMemberData(m){return{id:m.id,last:m.last||"",first:m.first||"",sex:m.sex||"",birth:m.birth||"",phone:m.phone||"",email:m.email||"",address:m.address||"",zip:m.zip||"",city:m.city||"",catOverride:m.catOverride||"",acts:Array.isArray(m.acts)?m.acts:[],due:Number(m.due||0),payments:Array.isArray(m.payments)?m.payments:[],comments:m.comments||"",medical_name:m.medical_name||"",created_at:m.created_at||"",original_version:Number(m.version||0)}}
function downloadBlob(blob,name){let a=document.createElement("a"),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function buildBackupPackage(sourceMembers,progressEl){if(currentRole!=="owner")throw new Error("Sauvegarde réservée au Propriétaire.");let members=[...(sourceMembers||[])].map(m=>({...m})),files={},manifest={format:"sgs-member-backup",formatVersion:1,appVersion:"15.3.6",createdAt:new Date().toISOString(),memberCount:members.length,members:[]};for(let i=0;i<members.length;i++){let m=members[i],entry={data:backupMemberData(m),photo:null,medical:null};if(progressEl)progressEl.textContent=`Préparation ${i+1}/${members.length} : ${m.first||""} ${m.last||""}`.trim();for(let kind of ["photo","medical"]){let path=kind==="photo"?m.photo_path:m.medical_path;if(!path)continue;let blob=await CloudStore.downloadMemberFile(path);if(!blob)throw new Error(`Document introuvable pour ${m.first} ${m.last}.`);let originalName=kind==="medical"?(m.medical_name||path.split("/").pop()):path.split("/").pop(),ext=safeBackupExt(path,originalName,blob.type),archivePath=`documents/${m.id}/${kind}.${ext}`,bytes=new Uint8Array(await blob.arrayBuffer());files[archivePath]=bytes;entry[kind]={archivePath,name:originalName||`${kind}.${ext}`,type:blob.type|| (ext==="pdf"?"application/pdf":"image/jpeg"),size:bytes.length}}manifest.members.push(entry)}files["backup.json"]=JSON.stringify(manifest,null,2);let blob=zipStore(files,"application/zip");return{blob,manifest,files}}
function backupFileName(prefix="SGS_Backup_Adherents"){let d=new Date(),pad=n=>String(n).padStart(2,"0");return`${prefix}_${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}_${pad(d.getHours())}${pad(d.getMinutes())}.zip`}
async function downloadFullBackup(){if(currentRole!=="owner"){alert("Sauvegarde réservée au Propriétaire.");return}if(backupRestoreBusy)return;backupRestoreBusy=true;backupDownloadBtn.disabled=true;try{backupProgress.textContent="Vérification des données et documents…";let pack=await buildBackupPackage(data,backupProgress);downloadBlob(pack.blob,backupFileName());backupProgress.textContent=`Sauvegarde créée : ${pack.manifest.memberCount} adhérent(s), photos et certificats inclus.`}catch(err){backupProgress.textContent="Échec de la sauvegarde.";alert("Sauvegarde impossible : "+err.message)}finally{backupRestoreBusy=false;backupDownloadBtn.disabled=false}}
function parseStoredZip(buffer){let b=new Uint8Array(buffer),dv=new DataView(buffer),dec=new TextDecoder(),files={},p=0;while(p+4<=b.length){let sig=dv.getUint32(p,true);if(sig===0x02014b50||sig===0x06054b50)break;if(sig!==0x04034b50)throw new Error("Archive ZIP invalide.");if(p+30>b.length)throw new Error("Archive ZIP tronquée.");let flags=dv.getUint16(p+6,true),method=dv.getUint16(p+8,true),crc=dv.getUint32(p+14,true),csize=dv.getUint32(p+18,true),usize=dv.getUint32(p+22,true),nlen=dv.getUint16(p+26,true),xlen=dv.getUint16(p+28,true);if(flags!==0||method!==0||csize!==usize)throw new Error("Format ZIP non pris en charge. Utilisez le fichier créé directement par SGS Gestion.");let ns=p+30,ds=ns+nlen+xlen,de=ds+csize;if(de>b.length)throw new Error("Archive ZIP incomplète.");let name=dec.decode(b.slice(ns,ns+nlen)),content=b.slice(ds,de);if(crc32(content)!==crc)throw new Error("Archive corrompue (contrôle CRC incorrect).");files[name]=content;p=de}return files}
function validateBackupPackage(files){if(!files["backup.json"])throw new Error("Le fichier backup.json est absent.");let manifest;try{manifest=JSON.parse(new TextDecoder().decode(files["backup.json"]))}catch(e){throw new Error("Le fichier backup.json est illisible.")}if(manifest.format!=="sgs-member-backup"||manifest.formatVersion!==1||!Array.isArray(manifest.members))throw new Error("Cette sauvegarde n’est pas compatible avec SGS Gestion.");if(Number(manifest.memberCount)!==manifest.members.length)throw new Error("Le nombre d’adhérents indiqué ne correspond pas au contenu.");let ids=new Set();for(let e of manifest.members){let m=e&&e.data;if(!m||typeof m.id!=="string"||!m.id)throw new Error("Une fiche adhérent est invalide.");if(ids.has(m.id))throw new Error("La sauvegarde contient un identifiant adhérent en double.");ids.add(m.id);if(!Array.isArray(m.acts)||!Array.isArray(m.payments))throw new Error(`Données invalides pour ${m.first||""} ${m.last||""}.`);if(m.created_at&&Number.isNaN(Date.parse(m.created_at)))throw new Error(`Date de création invalide pour ${m.first||""} ${m.last||""}.`);for(let kind of ["photo","medical"]){let d=e[kind];if(d&&(!d.archivePath||!files[d.archivePath]))throw new Error(`Document ${kind} manquant pour ${m.first||""} ${m.last||""}.`);if(d&&Number(d.size)!==files[d.archivePath].length)throw new Error(`Taille du document ${kind} incorrecte pour ${m.first||""} ${m.last||""}.`)}}return manifest}
function expectedRestoreWord(){return restoreMode.value==="missing"?"REINJECTER":restoreMode.value==="replace"?"RESTAURER":""}
function updateRestoreControls(){let hasBackup=!!loadedBackup&&!backupRestoreBusy;restoreMode.disabled=!hasBackup;let word=expectedRestoreWord();if(!hasBackup){restoreMode.value="";restoreConfirmText.value="";restoreConfirmText.disabled=true;restoreConfirmText.placeholder="Choisir un mode";restoreConfirmLabel.innerHTML="Choisissez d’abord un mode de restauration.";restoreStartBtn.disabled=true;return}if(!word){restoreConfirmText.value="";restoreConfirmText.disabled=true;restoreConfirmText.placeholder="Choisir un mode";restoreConfirmLabel.innerHTML="Choisissez d’abord un mode de restauration.";restoreStartBtn.disabled=true;return}restoreConfirmText.disabled=false;restoreConfirmText.placeholder=word;restoreConfirmLabel.innerHTML=restoreMode.value==="missing"?"Pour réinjecter les adhérents manquants, écrire exactement <b>REINJECTER</b>":"Pour remplacer tous les adhérents, écrire exactement <b>RESTAURER</b>";restoreStartBtn.disabled=restoreConfirmText.value.trim()!==word}
async function loadBackupFile(file){if(!file){loadedBackup=null;backupSummary.textContent="Aucun fichier de sauvegarde chargé.";updateRestoreControls();return}try{backupSummary.textContent="Vérification de la sauvegarde…";let files=parseStoredZip(await file.arrayBuffer()),manifest=validateBackupPackage(files);loadedBackup={manifest,files,fileName:file.name};let dt=new Date(manifest.createdAt),when=Number.isNaN(dt.getTime())?manifest.createdAt:dt.toLocaleString("fr-FR");backupSummary.style.whiteSpace="pre-line";backupSummary.textContent=`Sauvegarde valide\nDate : ${when}\nAdhérents : ${manifest.memberCount}\nFichier : ${file.name}`;restoreMode.value="";restoreConfirmText.value="";updateRestoreControls()}catch(err){loadedBackup=null;backupSummary.textContent="Sauvegarde invalide : "+err.message;updateRestoreControls()}}
function backupEntrySort(a,b){let ta=Date.parse(a.data.created_at||"")||0,tb=Date.parse(b.data.created_at||"")||0;return ta-tb||String(a.data.id).localeCompare(String(b.data.id))}
function fileFromBackup(entry,kind,files){let d=entry[kind];if(!d)return null;let bytes=files[d.archivePath];return new File([bytes],d.name||`${kind}.bin`,{type:d.type||"application/octet-stream",lastModified:Date.now()})}
async function restoreEntries(entries,files,progressEl){let sorted=[...entries].sort(backupEntrySort);for(let i=0;i<sorted.length;i++){let e=sorted[i],m={...e.data,version:0,photo_path:"",medical_path:"",photo_url:"",medical_url:""};if(progressEl)progressEl.textContent=`Restauration ${i+1}/${sorted.length} : ${m.first||""} ${m.last||""}`.trim();await CloudStore.restoreMember(m,fileFromBackup(e,"photo",files),fileFromBackup(e,"medical",files))}}
async function startSelectedRestore(){if(currentRole!=="owner"||!loadedBackup||backupRestoreBusy)return;let word=expectedRestoreWord();if(!word){alert("Choisissez d’abord un mode de restauration.");return}if(restoreConfirmText.value.trim()!==word){alert(`Écrivez exactement ${word} pour autoriser cette opération.`);return}if(restoreMode.value==="missing")await restoreMissingMembers();else if(restoreMode.value==="replace")await restoreReplaceMembers()}
async function restoreMissingMembers(){if(currentRole!=="owner"||!loadedBackup||backupRestoreBusy)return;if(restoreMode.value!=="missing"||restoreConfirmText.value.trim()!=="REINJECTER"){alert("Sélectionnez Réinjecter et écrivez exactement REINJECTER.");return}let existing=new Set(data.map(m=>m.id)),entries=loadedBackup.manifest.members.filter(e=>!existing.has(e.data.id));if(!entries.length){alert("Tous les adhérents de cette sauvegarde sont déjà présents.");return}if(!confirm(`CONFIRMATION : réinjecter ${entries.length} adhérent(s) manquant(s) ? Les fiches déjà présentes ne seront pas modifiées.`))return;backupRestoreBusy=true;updateRestoreControls();try{restoreProgress.textContent="Réinjection en cours…";await restoreEntries(entries,loadedBackup.files,restoreProgress);restoreProgress.textContent=`Terminé : ${entries.length} adhérent(s) réinjecté(s).`;restoreConfirmText.value="";await refreshData();alert("Réinjection terminée avec succès.")}catch(err){restoreProgress.textContent="Restauration interrompue.";alert("Réinjection interrompue : "+err.message)}finally{backupRestoreBusy=false;updateRestoreControls()}}
async function restoreReplaceMembers(){if(currentRole!=="owner"||!loadedBackup||backupRestoreBusy)return;if(restoreMode.value!=="replace"||restoreConfirmText.value.trim()!=="RESTAURER"){alert("Sélectionnez Remplacer tous les adhérents et écrivez exactement RESTAURER.");return}if(!confirm(`ATTENTION : les ${data.length} adhérent(s) actuels vont être remplacés par les ${loadedBackup.manifest.memberCount} adhérent(s) de la sauvegarde. Continuer ?`))return;backupRestoreBusy=true;updateRestoreControls();let emergency=null;try{restoreProgress.textContent="Création obligatoire d’une sauvegarde de secours de la base actuelle…";emergency=await buildBackupPackage(data,restoreProgress);downloadBlob(emergency.blob,backupFileName("SGS_SAUVEGARDE_SECOURS_AVANT_RESTAURATION"));if(!confirm("La sauvegarde de secours vient d’être téléchargée. Vérifiez qu’elle est bien présente dans vos Téléchargements avant de continuer.\n\nOK = poursuivre le remplacement\nAnnuler = ne rien supprimer")){restoreProgress.textContent="Restauration annulée. Aucune donnée n’a été supprimée.";return}restoreProgress.textContent="Sauvegarde de secours confirmée. Remplacement de la base…";await CloudStore.deleteAllMembers();await restoreEntries(loadedBackup.manifest.members,loadedBackup.files,restoreProgress);restoreProgress.textContent=`Restauration terminée : ${loadedBackup.manifest.memberCount} adhérent(s).`;restoreConfirmText.value="";restoreMode.value="";await refreshData();alert("Restauration complète terminée avec succès.")}catch(err){let original=err;restoreProgress.textContent="Erreur pendant la restauration. Tentative de retour automatique à la base précédente…";if(emergency){try{await CloudStore.deleteAllMembers();await restoreEntries(emergency.manifest.members,emergency.files,restoreProgress);await refreshData();restoreProgress.textContent="La restauration demandée a échoué, mais la base précédente a été rétablie automatiquement.";alert("La restauration a échoué : "+original.message+"\n\nLa base précédente a été rétablie automatiquement. Conservez aussi le fichier de sauvegarde de secours téléchargé.")}catch(recoveryErr){restoreProgress.textContent="ÉCHEC DE RÉCUPÉRATION AUTOMATIQUE. Utilisez le fichier de sauvegarde de secours téléchargé.";alert("Erreur de restauration : "+original.message+"\nErreur de récupération : "+recoveryErr.message+"\n\nN’effectuez plus de modification. Utilisez la sauvegarde de secours téléchargée pour restaurer la base.")}}else{alert("Restauration impossible avant toute suppression : "+original.message)}}finally{backupRestoreBusy=false;updateRestoreControls()}}

function applyRole(){let role=currentRole;document.querySelectorAll(".ownerOnly").forEach(el=>el.classList.toggle("hiddenOwner",role!=="owner"));document.querySelectorAll(".adminOnly").forEach(el=>el.classList.toggle("hiddenAdmin",role==="coach"));if(role==="coach"){document.querySelectorAll(".tab").forEach(x=>x.classList.remove("on"));document.querySelectorAll("main section").forEach(s=>s.classList.add("hide"));document.querySelector('[data-p="coach"]').classList.add("on");coach.classList.remove("hide")}}
async function refreshData(){if(refreshing||!currentRole)return;refreshing=true;try{[data,trials]=await Promise.all([CloudStore.loadMembers(currentRole),CloudStore.loadTrials()]);selectedMembers=new Set([...selectedMembers].filter(id=>data.some(m=>m.id===id)));selectedTrials=new Set([...selectedTrials].filter(id=>trials.some(t=>t.id===id)));render();if(eid&&formM.classList.contains("open")){let latest=data.find(x=>x.id===eid);if(!latest||Number(latest.version)!==editVersion)formWarning.textContent="Cette fiche vient d’être modifiée par une autre personne. Fermez-la puis ouvrez-la à nouveau."}}finally{refreshing=false}}
function scheduleRefresh(){if(backupRestoreBusy)return;clearTimeout(refreshTimer);refreshTimer=setTimeout(refreshData,250)}
async function startApp(){let session=await CloudStore.session();if(!session){loginScreen.classList.remove("hidden");return}try{currentRole=await CloudStore.role();roleBadge.textContent={owner:"Propriétaire",admin:"Administrateur",coach:"Coach"}[currentRole]||currentRole;loginScreen.classList.add("hidden");await refreshData();CloudStore.watch(scheduleRefresh)}catch(err){loginError.textContent=err.message;loginScreen.classList.remove("hidden")}}
loginForm.onsubmit=async e=>{e.preventDefault();loginError.textContent="";try{await CloudStore.login(loginEmail.value,loginPassword.value);await startApp()}catch(err){loginError.textContent="Connexion refusée : "+err.message}};
showPassword.onchange=()=>{loginPassword.type=showPassword.checked?"text":"password"};
function showPasswordRecovery(){recoveryScreen.classList.remove("hidden");loginScreen.classList.add("hidden")}
showRecoveryPassword.onchange=()=>{let t=showRecoveryPassword.checked?"text":"password";recoveryPassword.type=t;recoveryPassword2.type=t};
recoveryForm.onsubmit=async e=>{e.preventDefault();recoveryError.textContent="";recoverySuccess.textContent="";let p1=recoveryPassword.value,p2=recoveryPassword2.value;if(p1.length<8){recoveryError.textContent="Le mot de passe doit contenir au moins 8 caractères.";return}if(p1!==p2){recoveryError.textContent="Les deux mots de passe ne correspondent pas.";return}recoverySubmit.disabled=true;try{await CloudStore.updatePassword(p1);recoverySuccess.textContent="Mot de passe modifié avec succès.";setTimeout(async()=>{await CloudStore.logout();location.replace(location.origin+location.pathname)},900)}catch(err){recoveryError.textContent="Impossible de modifier le mot de passe : "+err.message;recoverySubmit.disabled=false}};
CloudStore.onAuthStateChange((event)=>{if(event==="PASSWORD_RECOVERY")showPasswordRecovery()});
if(location.hash.includes("type=recovery")||location.search.includes("type=recovery"))showPasswordRecovery();
logoutBtn.onclick=async()=>{await CloudStore.logout();location.reload()};window.addEventListener("focus",scheduleRefresh);document.addEventListener("visibilitychange",()=>{if(!document.hidden)scheduleRefresh()});if(document.getElementById("exportExcelBtn"))exportExcelBtn.onclick=exportExcel;if(document.getElementById("backupFileInput"))backupFileInput.addEventListener("change",()=>loadBackupFile(backupFileInput.files&&backupFileInput.files[0]));if(document.getElementById("restoreMode"))restoreMode.addEventListener("change",()=>{restoreConfirmText.value="";updateRestoreControls()});if(document.getElementById("restoreConfirmText"))restoreConfirmText.addEventListener("input",updateRestoreControls);updateRestoreControls();setupDocumentInputs();if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));startApp();
let deferredInstallPrompt=null;const installRequested=new URLSearchParams(location.search).get("install")==="1";const standalone=matchMedia("(display-mode: standalone)").matches||navigator.standalone===true;const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);function cleanInstallUrl(){let u=new URL(location.href);u.searchParams.delete("install");history.replaceState({},"",u.pathname+(u.search?u.search:"")+u.hash)}function showInstallChoice(){if(installRequested&&!standalone)installChoice.classList.remove("hide")}window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstallPrompt=e;if(installRequested&&!standalone){installNow.disabled=false;installNow.textContent="Installer l’application";showInstallChoice()}});installNow.onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();let choice=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;cleanInstallUrl();installChoice.classList.add("hide");if(choice.outcome!=="accepted")installHelp.textContent="Installation annulée. Vous pouvez continuer sur le web.";return}if(isiOS){installHelp.textContent="Sur iPhone ou iPad : ouvrez ce lien dans Safari, touchez Partager, puis Sur l’écran d’accueil."}else{installHelp.textContent="L’installation automatique n’est pas proposée ici. Dans Chrome ou Edge, ouvrez le menu du navigateur puis choisissez Installer l’application."}installNow.disabled=true;installNow.textContent="Instructions affichées"};useWeb.onclick=()=>{cleanInstallUrl();installChoice.classList.add("hide")};window.addEventListener("appinstalled",()=>{deferredInstallPrompt=null;cleanInstallUrl();installChoice.classList.add("hide")});if(installRequested&&!standalone){showInstallChoice();setTimeout(()=>{if(!deferredInstallPrompt){installNow.disabled=false;installNow.textContent=isiOS?"Voir les instructions iPhone/iPad":"Afficher les instructions d’installation"}},1800)}
